# Generated by Django 3.0.6 on 2020-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(db_index=True, protocol='ipv4', verbose_name='IP地址')),
                ('hostname', models.CharField(db_index=True, max_length=32, verbose_name='主机名')),
                ('status', models.SmallIntegerField(choices=[(0, 'downline'), (1, 'online')], default=0, verbose_name='主机状态')),
                ('information', models.TextField(max_length=128, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
